#include "widget.h"
#include "ui_widget.h"
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QFile>
#include <QDebug>
#include <QString>
#include <QMap>
#include <QMetaType>
#include "transmap.h"


QMap<QString,QString> tableMap;

Widget::Widget(QWidget *parent)
    : QWidget(parent)
    , ui(new Ui::Widget)
{
    ui->setupUi(this);
    createView();

    createMap();


    qDebug()<<tableMap.value("TM-RCES-238");

    qRegisterMetaType<QVariant>("QVariant");

    QVariant mapVar;
    mapVar.setValue(tableMap);

    TransMap * transMap = new TransMap();

    connect(this,&Widget::SendMap,transMap,&TransMap::GetMap);
    connect(ui->btn,&QPushButton::clicked,[=](){
        emit SendMap(mapVar);
    });

}

Widget::~Widget()
{
    delete ui;
}

void Widget::createView()
{
    QFile file("C:/Users/LPY/Desktop/dataParse.json");
    file.open(QIODevice::ReadOnly | QIODevice::Text);
    QString value = file.readAll();
    file.close();

    QJsonParseError parseJsonErr;
    QJsonDocument document = QJsonDocument::fromJson(value.toUtf8(),&parseJsonErr);
    if(!(parseJsonErr.error == QJsonParseError::NoError))
    {
        qDebug()<<tr("解析json文件错误！");
        return;
    }
    QJsonObject jsonObject = document.object();
    QJsonValue configValueList = jsonObject.value(QStringLiteral("config"));


    foreach(QString i, configValueList.toObject().keys()){
        QJsonArray array = configValueList.toObject().value(i).toArray();
        qDebug()<<array;
    }


    if(jsonObject.contains(QStringLiteral("parse")))
    {
        QJsonValue arrayValue = jsonObject.value(QStringLiteral("parse"));
        if(arrayValue.isArray())
        {
            QJsonArray parseArray = arrayValue.toArray();
            for (int i = 0; i<parseArray.size(); i++ ) {
                QJsonObject parseItem = parseArray.at(i).toObject();
                QJsonObject item = parseItem.begin()->toObject();
                QString attribute = item.value(QStringLiteral("attribute")).toString();
                QJsonArray locationArray = item.value(QStringLiteral("location")).toArray();
                qDebug()<<"attribute:"<< attribute;
                switch (attribute.toInt()) {
                case 0:
                {
                    qDebug()<<"name:"<<item.value(QStringLiteral("name")).toString();
                    for (int k = 0;k<4 ;k++ ) {
                        qDebug()<<locationArray.at(k).toInt();

                    }
                    QJsonObject flag = item.value(QStringLiteral("flag")).toObject();
                    foreach(QString i, flag.keys())
                    {
                        qDebug()<<i<<flag.value(i).toString();
                    }
                    break;
                }
                case 1:
                {
                    qDebug()<<"name:"<<item.value(QStringLiteral("name")).toString();
                    for (int k = 0;k<4 ;k++ ) {
                        qDebug()<<locationArray.at(k).toInt();

                    }
                    QJsonArray trans = item.value(QStringLiteral("trans")).toArray();
                    for (int k = 0;k<trans.size();k++ ) {
                        qDebug()<<trans.at(k).toString();
                    }
                    break;
                }
                case 2:
                {
                    qDebug()<<"name:"<<item.value(QStringLiteral("name")).toString();
                    for (int k = 0;k<4 ;k++ ) {
                        qDebug()<<locationArray.at(k).toInt();

                    }
                    QJsonArray trans = item.value(QStringLiteral("trans")).toArray();
                    for (int k = 0;k<trans.size();k++ ) {
                        qDebug()<<trans.at(k).toString();
                    }
                    break;
                }
                case 3:
                {
                    qDebug()<<"name:"<<item.value(QStringLiteral("name")).toString();
                    if(item.contains(QStringLiteral("X")))
                    {
                        QJsonObject itemX = item.value(QStringLiteral("X")).toObject();
                        QJsonArray locationArray = itemX.value(QStringLiteral("location")).toArray();
                        for (int k = 0 ; k<locationArray.size(); k++ ) {
                            qDebug()<<locationArray.at(k).toInt();
                        }
                        QJsonArray transArray = itemX.value(QStringLiteral("trans")).toArray();
                        for (int k = 0 ; k<transArray.size(); k++ ) {
                            qDebug()<<transArray.at(k).toString();
                        }
                    }
                    if(item.contains(QStringLiteral("Y")))
                    {
                        QJsonObject itemX = item.value(QStringLiteral("Y")).toObject();
                        QJsonArray locationArray = itemX.value(QStringLiteral("location")).toArray();
                        for (int k = 0 ; k<locationArray.size(); k++ ) {
                            qDebug()<<locationArray.at(k).toInt();
                        }
                        QJsonArray transArray = itemX.value(QStringLiteral("trans")).toArray();
                        for (int k = 0 ; k<transArray.size(); k++ ) {
                            qDebug()<<transArray.at(k).toString();
                        }
                    }
                    if(item.contains(QStringLiteral("Z")))
                    {
                        QJsonObject itemX = item.value(QStringLiteral("Z")).toObject();
                        QJsonArray locationArray = itemX.value(QStringLiteral("location")).toArray();
                        for (int k = 0 ; k<locationArray.size(); k++ ) {
                            qDebug()<<locationArray.at(k).toInt();
                        }
                        QJsonArray transArray = itemX.value(QStringLiteral("trans")).toArray();
                        for (int k = 0 ; k<transArray.size(); k++ ) {
                            qDebug()<<transArray.at(k).toString();
                        }
                    }
                    break;
                }
                }
            }
        }
    }




}


void Widget::createMap()
{
    int i = 0;
    tableMap.insert("TM-RDTTCA-01",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-02",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-03",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-04",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-05",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-06",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-07",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-08",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-09",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-10",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-11",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-12",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-13",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-14",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-15",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-16",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-17",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-18",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-19",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-20",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-21",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-22",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-23",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-24",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-25",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-26",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-27",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-28",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-29",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-30",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-31",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-32",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-33",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-34",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-35",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-36",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-37",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-38",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-39",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-40",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-41",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-42",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-43",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-44",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-45",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-46",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-47",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-48",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-49",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-50",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-51",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-52",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-53",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-54",QString::number(i));i++;
    tableMap.insert("TM-RDTTCA-55",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-01",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-02",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-03",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-04",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-05",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-06",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-07",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-08",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-09",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-10",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-11",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-12",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-13",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-14",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-15",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-16",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-17",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-18",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-19",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-20",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-21",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-22",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-23",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-24",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-25",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-26",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-27",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-28",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-29",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-30",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-31",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-32",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-33",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-34",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-35",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-36",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-37",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-38",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-39",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-40",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-41",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-42",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-43",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-44",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-45",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-46",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-47",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-48",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-49",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-50",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-51",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-52",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-53",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-54",QString::number(i));i++;
    tableMap.insert("TM-RDTTCB-55",QString::number(i));i++;
    tableMap.insert("TM-ROCS-01",QString::number(i));i++;
    tableMap.insert("TM-ROCS-02",QString::number(i));i++;
    tableMap.insert("TM-ROCS-03",QString::number(i));i++;
    tableMap.insert("TM-ROCS-04",QString::number(i));i++;
    tableMap.insert("TM-ROCS-05",QString::number(i));i++;
    tableMap.insert("TM-ROCS-06",QString::number(i));i++;
    tableMap.insert("TM-ROCS-07",QString::number(i));i++;
    tableMap.insert("TM-ROCS-08",QString::number(i));i++;
    tableMap.insert("TM-ROCS-09",QString::number(i));i++;
    tableMap.insert("TM-ROCS-10",QString::number(i));i++;
    tableMap.insert("TM-ROCS-11",QString::number(i));i++;
    tableMap.insert("TM-ROCS-12",QString::number(i));i++;
    tableMap.insert("TM-ROCS-13",QString::number(i));i++;
    tableMap.insert("TM-ROCS-14",QString::number(i));i++;
    tableMap.insert("TM-ROCS-15",QString::number(i));i++;
    tableMap.insert("TM-ROCS-16",QString::number(i));i++;
    tableMap.insert("TM-ROCS-17",QString::number(i));i++;
    tableMap.insert("TM-ROCS-18",QString::number(i));i++;
    tableMap.insert("TM-ROCS-19",QString::number(i));i++;
    tableMap.insert("TM-ROCS-20",QString::number(i));i++;
    tableMap.insert("TM-ROCS-21",QString::number(i));i++;
    tableMap.insert("TM-ROCS-22",QString::number(i));i++;
    tableMap.insert("TM-ROCS-23",QString::number(i));i++;
    tableMap.insert("TM-ROCS-24",QString::number(i));i++;
    tableMap.insert("TM-ROCS-25",QString::number(i));i++;
    tableMap.insert("TM-ROCS-26",QString::number(i));i++;
    tableMap.insert("TM-ROCS-27",QString::number(i));i++;
    tableMap.insert("TM-ROCS-28",QString::number(i));i++;
    tableMap.insert("TM-ROCS-29",QString::number(i));i++;
    tableMap.insert("TM-ROCS-30",QString::number(i));i++;
    tableMap.insert("TM-ROCS-31",QString::number(i));i++;
    tableMap.insert("TM-ROCS-32",QString::number(i));i++;
    tableMap.insert("TM-ROCS-33",QString::number(i));i++;
    tableMap.insert("TM-ROCS-34",QString::number(i));i++;
    tableMap.insert("TM-ROCS-35",QString::number(i));i++;
    tableMap.insert("TM-ROCS-36",QString::number(i));i++;
    tableMap.insert("TM-ROCS-37",QString::number(i));i++;
    tableMap.insert("TM-ROCS-38",QString::number(i));i++;
    tableMap.insert("TM-ROCS-39",QString::number(i));i++;
    tableMap.insert("TM-ROCS-40",QString::number(i));i++;
    tableMap.insert("TM-ROCS-41",QString::number(i));i++;
    tableMap.insert("TM-ROCS-42",QString::number(i));i++;
    tableMap.insert("TM-ROCS-43",QString::number(i));i++;
    tableMap.insert("TM-ROCS-44",QString::number(i));i++;
    tableMap.insert("TM-ROCS-45",QString::number(i));i++;
    tableMap.insert("TM-ROCS-46",QString::number(i));i++;
    tableMap.insert("TM-ROCS-47",QString::number(i));i++;
    tableMap.insert("TM-ROCS-48",QString::number(i));i++;
    tableMap.insert("TM-ROCS-49",QString::number(i));i++;
    tableMap.insert("TM-ROCS-50",QString::number(i));i++;
    tableMap.insert("TM-ROCS-51",QString::number(i));i++;
    tableMap.insert("TM-ROCS-52",QString::number(i));i++;
    tableMap.insert("TM-ROCS-53",QString::number(i));i++;
    tableMap.insert("TM-ROCS-54",QString::number(i));i++;
    tableMap.insert("TM-ROCS-55",QString::number(i));i++;
    tableMap.insert("TM-ROCS-56",QString::number(i));i++;
    tableMap.insert("TM-ROCS-57",QString::number(i));i++;
    tableMap.insert("TM-ROCS-58",QString::number(i));i++;
    tableMap.insert("TM-ROCS-59",QString::number(i));i++;
    tableMap.insert("TM-ROCS-60",QString::number(i));i++;
    tableMap.insert("TM-ROCS-61",QString::number(i));i++;
    tableMap.insert("TM-ROCS-62",QString::number(i));i++;
    tableMap.insert("TM-ROCS-63",QString::number(i));i++;
    tableMap.insert("TM-RADCS-01",QString::number(i));i++;
    tableMap.insert("TM-RADCS-02",QString::number(i));i++;
    tableMap.insert("TM-RADCS-03",QString::number(i));i++;
    tableMap.insert("TM-RADCS-04",QString::number(i));i++;
    tableMap.insert("TM-RADCS-05",QString::number(i));i++;
    tableMap.insert("TM-RADCS-06",QString::number(i));i++;
    tableMap.insert("TM-RADCS-07",QString::number(i));i++;
    tableMap.insert("TM-RADCS-08",QString::number(i));i++;
    tableMap.insert("TM-RADCS-09",QString::number(i));i++;
    tableMap.insert("TM-RADCS-10",QString::number(i));i++;
    tableMap.insert("TM-RADCS-11",QString::number(i));i++;
    tableMap.insert("TM-RADCS-12",QString::number(i));i++;
    tableMap.insert("TM-RADCS-13",QString::number(i));i++;
    tableMap.insert("TM-RADCS-14",QString::number(i));i++;
    tableMap.insert("TM-RADCS-15",QString::number(i));i++;
    tableMap.insert("TM-RADCS-16",QString::number(i));i++;
    tableMap.insert("TM-RADCS-17",QString::number(i));i++;
    tableMap.insert("TM-RADCS-18",QString::number(i));i++;
    tableMap.insert("TM-RADCS-19",QString::number(i));i++;
    tableMap.insert("TM-RADCS-20",QString::number(i));i++;
    tableMap.insert("TM-RADCS-21",QString::number(i));i++;
    tableMap.insert("TM-RADCS-22",QString::number(i));i++;
    tableMap.insert("TM-RADCS-23",QString::number(i));i++;
    tableMap.insert("TM-RADCS-24",QString::number(i));i++;
    tableMap.insert("TM-RADCS-25",QString::number(i));i++;
    tableMap.insert("TM-RADCS-26",QString::number(i));i++;
    tableMap.insert("TM-RADCS-27",QString::number(i));i++;
    tableMap.insert("TM-RADCS-28",QString::number(i));i++;
    tableMap.insert("TM-RADCS-29",QString::number(i));i++;
    tableMap.insert("TM-RADCS-30",QString::number(i));i++;
    tableMap.insert("TM-RADCS-31",QString::number(i));i++;
    tableMap.insert("TM-RADCS-32",QString::number(i));i++;
    tableMap.insert("TM-RADCS-33",QString::number(i));i++;
    tableMap.insert("TM-RADCS-34",QString::number(i));i++;
    tableMap.insert("TM-RADCS-35",QString::number(i));i++;
    tableMap.insert("TM-RADCS-36",QString::number(i));i++;
    tableMap.insert("TM-RADCS-37",QString::number(i));i++;
    tableMap.insert("TM-RADCS-38",QString::number(i));i++;
    tableMap.insert("TM-RADCS-39",QString::number(i));i++;
    tableMap.insert("TM-RADCS-40",QString::number(i));i++;
    tableMap.insert("TM-RADCS-41",QString::number(i));i++;
    tableMap.insert("TM-RADCS-42",QString::number(i));i++;
    tableMap.insert("TM-RADCS-43",QString::number(i));i++;
    tableMap.insert("TM-RADCS-44",QString::number(i));i++;
    tableMap.insert("TM-RADCS-45",QString::number(i));i++;
    tableMap.insert("TM-RADCS-46",QString::number(i));i++;
    tableMap.insert("TM-RADCS-47",QString::number(i));i++;
    tableMap.insert("TM-RADCS-48",QString::number(i));i++;
    tableMap.insert("TM-RADCS-49",QString::number(i));i++;
    tableMap.insert("TM-RADCS-50",QString::number(i));i++;
    tableMap.insert("TM-RADCS-51",QString::number(i));i++;
    tableMap.insert("TM-RADCS-52",QString::number(i));i++;
    tableMap.insert("TM-RADCS-53",QString::number(i));i++;
    tableMap.insert("TM-RADCS-54",QString::number(i));i++;
    tableMap.insert("TM-RADCS-55",QString::number(i));i++;
    tableMap.insert("TM-RADCS-56",QString::number(i));i++;
    tableMap.insert("TM-RADCS-57",QString::number(i));i++;
    tableMap.insert("TM-RADCS-58",QString::number(i));i++;
    tableMap.insert("TM-RADCS-59",QString::number(i));i++;
    tableMap.insert("TM-RADCS-60",QString::number(i));i++;
    tableMap.insert("TM-RADCS-61",QString::number(i));i++;
    tableMap.insert("TM-RADCS-62",QString::number(i));i++;
    tableMap.insert("TM-RADCS-63",QString::number(i));i++;
    tableMap.insert("TM-RADCS-64",QString::number(i));i++;
    tableMap.insert("TM-RADCS-65",QString::number(i));i++;
    tableMap.insert("TM-RADCS-66",QString::number(i));i++;
    tableMap.insert("TM-RADCS-67",QString::number(i));i++;
    tableMap.insert("TM-RADCS-68",QString::number(i));i++;
    tableMap.insert("TM-RADCS-69",QString::number(i));i++;
    tableMap.insert("TM-RADCS-70",QString::number(i));i++;
    tableMap.insert("TM-RADCS-71",QString::number(i));i++;
    tableMap.insert("TM-RADCS-72",QString::number(i));i++;
    tableMap.insert("TM-RADCS-73",QString::number(i));i++;
    tableMap.insert("TM-RADCS-74",QString::number(i));i++;
    tableMap.insert("TM-RADCS-75",QString::number(i));i++;
    tableMap.insert("TM-RADCS-76",QString::number(i));i++;
    tableMap.insert("TM-RADCS-77",QString::number(i));i++;
    tableMap.insert("TM-RADCS-78",QString::number(i));i++;
    tableMap.insert("TM-RADCS-79",QString::number(i));i++;
    tableMap.insert("TM-RADCS-80",QString::number(i));i++;
    tableMap.insert("TM-RADCS-81",QString::number(i));i++;
    tableMap.insert("TM-RADCS-82",QString::number(i));i++;
    tableMap.insert("TM-RADCS-83",QString::number(i));i++;
    tableMap.insert("TM-RADCS-84",QString::number(i));i++;
    tableMap.insert("TM-RADCS-85",QString::number(i));i++;
    tableMap.insert("TM-RADCS-86",QString::number(i));i++;
    tableMap.insert("TM-RADCS-87",QString::number(i));i++;
    tableMap.insert("TM-RADCS-88",QString::number(i));i++;
    tableMap.insert("TM-RADCS-89",QString::number(i));i++;
    tableMap.insert("TM-RADCS-90",QString::number(i));i++;
    tableMap.insert("TM-RADCS-91",QString::number(i));i++;
    tableMap.insert("TM-RADCS-92",QString::number(i));i++;
    tableMap.insert("TM-RADCS-93",QString::number(i));i++;
    tableMap.insert("TM-RADCS-94",QString::number(i));i++;
    tableMap.insert("TM-RADCS-95",QString::number(i));i++;
    tableMap.insert("TM-RADCS-96",QString::number(i));i++;
    tableMap.insert("TM-RADCS-97",QString::number(i));i++;
    tableMap.insert("TM-RADCS-98",QString::number(i));i++;
    tableMap.insert("TM-RADCS-99",QString::number(i));i++;
    tableMap.insert("TM-RADCS-100",QString::number(i));i++;
    tableMap.insert("TM-RADCS-101",QString::number(i));i++;
    tableMap.insert("TM-RADCS-102",QString::number(i));i++;
    tableMap.insert("TM-RADCS-103",QString::number(i));i++;
    tableMap.insert("TM-RADCS-104",QString::number(i));i++;
    tableMap.insert("TM-RADCS-105",QString::number(i));i++;
    tableMap.insert("TM-RADCS-106",QString::number(i));i++;
    tableMap.insert("TM-RADCS-107",QString::number(i));i++;
    tableMap.insert("TM-RADCS-108",QString::number(i));i++;
    tableMap.insert("TM-RADCS-109",QString::number(i));i++;
    tableMap.insert("TM-RADCS-110",QString::number(i));i++;
    tableMap.insert("TM-RADCS-111",QString::number(i));i++;
    tableMap.insert("TM-RADCS-112",QString::number(i));i++;
    tableMap.insert("TM-RADCS-113",QString::number(i));i++;
    tableMap.insert("TM-RADCS-114",QString::number(i));i++;
    tableMap.insert("TM-RADCS-115",QString::number(i));i++;
    tableMap.insert("TM-RADCS-116",QString::number(i));i++;
    tableMap.insert("TM-RADCS-117",QString::number(i));i++;
    tableMap.insert("TM-RADCS-118",QString::number(i));i++;
    tableMap.insert("TM-RADCS-119",QString::number(i));i++;
    tableMap.insert("TM-RADCS-120",QString::number(i));i++;
    tableMap.insert("TM-RADCS-121",QString::number(i));i++;
    tableMap.insert("TM-RADCS-122",QString::number(i));i++;
    tableMap.insert("TM-RADCS-123",QString::number(i));i++;
    tableMap.insert("TM-RADCS-124",QString::number(i));i++;
    tableMap.insert("TM-RADCS-125",QString::number(i));i++;
    tableMap.insert("TM-RADCS-126",QString::number(i));i++;
    tableMap.insert("TM-RADCS-127",QString::number(i));i++;
    tableMap.insert("TM-RADCS-128",QString::number(i));i++;
    tableMap.insert("TM-RADCS-129",QString::number(i));i++;
    tableMap.insert("TM-RADCS-130",QString::number(i));i++;
    tableMap.insert("TM-RADCS-131",QString::number(i));i++;
    tableMap.insert("TM-RADCS-132",QString::number(i));i++;
    tableMap.insert("TM-RADCS-133",QString::number(i));i++;
    tableMap.insert("TM-RADCS-134",QString::number(i));i++;
    tableMap.insert("TM-RADCS-135",QString::number(i));i++;
    tableMap.insert("TM-RADCS-136",QString::number(i));i++;
    tableMap.insert("TM-RADCS-137",QString::number(i));i++;
    tableMap.insert("TM-RADCS-138",QString::number(i));i++;
    tableMap.insert("TM-RADCS-139",QString::number(i));i++;
    tableMap.insert("TM-RADCS-140",QString::number(i));i++;
    tableMap.insert("TM-RADCS-141",QString::number(i));i++;
    tableMap.insert("TM-RADCS-142",QString::number(i));i++;
    tableMap.insert("TM-RADCS-143",QString::number(i));i++;
    tableMap.insert("TM-RADCS-144",QString::number(i));i++;
    tableMap.insert("TM-RADCS-145",QString::number(i));i++;
    tableMap.insert("TM-RADCS-146",QString::number(i));i++;
    tableMap.insert("TM-RADCS-147",QString::number(i));i++;
    tableMap.insert("TM-RADCS-148",QString::number(i));i++;
    tableMap.insert("TM-RADCS-149",QString::number(i));i++;
    tableMap.insert("TM-RADCS-150",QString::number(i));i++;
    tableMap.insert("TM-RADCS-151",QString::number(i));i++;
    tableMap.insert("TM-RADCS-152",QString::number(i));i++;
    tableMap.insert("TM-RADCS-153",QString::number(i));i++;
    tableMap.insert("TM-RADCS-154",QString::number(i));i++;
    tableMap.insert("TM-RADCS-155",QString::number(i));i++;
    tableMap.insert("TM-RADCS-156",QString::number(i));i++;
    tableMap.insert("TM-RADCS-157",QString::number(i));i++;
    tableMap.insert("TM-RADCS-158",QString::number(i));i++;
    tableMap.insert("TM-RADCS-159",QString::number(i));i++;
    tableMap.insert("TM-RADCS-160",QString::number(i));i++;
    tableMap.insert("TM-RADCS-161",QString::number(i));i++;
    tableMap.insert("TM-RADCS-162",QString::number(i));i++;
    tableMap.insert("TM-RADCS-163",QString::number(i));i++;
    tableMap.insert("TM-RADCS-164",QString::number(i));i++;
    tableMap.insert("TM-RADCS-165",QString::number(i));i++;
    tableMap.insert("TM-RADCS-166",QString::number(i));i++;
    tableMap.insert("TM-RADCS-167",QString::number(i));i++;
    tableMap.insert("TM-RADCS-168",QString::number(i));i++;
    tableMap.insert("TM-RADCS-169",QString::number(i));i++;
    tableMap.insert("TM-RADCS-170",QString::number(i));i++;
    tableMap.insert("TM-RADCS-171",QString::number(i));i++;
    tableMap.insert("TM-RADCS-172",QString::number(i));i++;
    tableMap.insert("TM-RADCS-173",QString::number(i));i++;
    tableMap.insert("TM-REPS-01",QString::number(i));i++;
    tableMap.insert("TM-REPS-02",QString::number(i));i++;
    tableMap.insert("TM-REPS-03",QString::number(i));i++;
    tableMap.insert("TM-REPS-04",QString::number(i));i++;
    tableMap.insert("TM-REPS-05",QString::number(i));i++;
    tableMap.insert("TM-REPS-06",QString::number(i));i++;
    tableMap.insert("TM-REPS-07",QString::number(i));i++;
    tableMap.insert("TM-REPS-08",QString::number(i));i++;
    tableMap.insert("TM-REPS-09",QString::number(i));i++;
    tableMap.insert("TM-REPS-10",QString::number(i));i++;
    tableMap.insert("TM-REPS-11",QString::number(i));i++;
    tableMap.insert("TM-REPS-12",QString::number(i));i++;
    tableMap.insert("TM-REPS-13",QString::number(i));i++;
    tableMap.insert("TM-REPS-14",QString::number(i));i++;
    tableMap.insert("TM-REPS-15",QString::number(i));i++;
    tableMap.insert("TM-REPS-16",QString::number(i));i++;
    tableMap.insert("TM-REPS-17",QString::number(i));i++;
    tableMap.insert("TM-REPS-18",QString::number(i));i++;
    tableMap.insert("TM-REPS-19",QString::number(i));i++;
    tableMap.insert("TM-REPS-20",QString::number(i));i++;
    tableMap.insert("TM-REPS-21",QString::number(i));i++;
    tableMap.insert("TM-REPS-22",QString::number(i));i++;
    tableMap.insert("TM-REPS-23",QString::number(i));i++;
    tableMap.insert("TM-REPS-24",QString::number(i));i++;
    tableMap.insert("TM-REPS-25",QString::number(i));i++;
    tableMap.insert("TM-REPS-26",QString::number(i));i++;
    tableMap.insert("TM-REPS-27",QString::number(i));i++;
    tableMap.insert("TM-REPS-28",QString::number(i));i++;
    tableMap.insert("TM-REPS-29",QString::number(i));i++;
    tableMap.insert("TM-REPS-30",QString::number(i));i++;
    tableMap.insert("TM-REPS-31",QString::number(i));i++;
    tableMap.insert("TM-REPS-32",QString::number(i));i++;
    tableMap.insert("TM-REPS-33",QString::number(i));i++;
    tableMap.insert("TM-REPS-34",QString::number(i));i++;
    tableMap.insert("TM-REPS-35",QString::number(i));i++;
    tableMap.insert("TM-REPS-36",QString::number(i));i++;
    tableMap.insert("TM-REPS-37",QString::number(i));i++;
    tableMap.insert("TM-REPS-38",QString::number(i));i++;
    tableMap.insert("TM-REPS-39",QString::number(i));i++;
    tableMap.insert("TM-REPS-40",QString::number(i));i++;
    tableMap.insert("TM-REPS-41",QString::number(i));i++;
    tableMap.insert("TM-REPS-42",QString::number(i));i++;
    tableMap.insert("TM-REPS-43",QString::number(i));i++;
    tableMap.insert("TM-REPS-44",QString::number(i));i++;
    tableMap.insert("TM-REPS-45",QString::number(i));i++;
    tableMap.insert("TM-REPS-46",QString::number(i));i++;
    tableMap.insert("TM-REPS-47",QString::number(i));i++;
    tableMap.insert("TM-REPS-48",QString::number(i));i++;
    tableMap.insert("TM-REPS-49",QString::number(i));i++;
    tableMap.insert("TM-REPS-50",QString::number(i));i++;
    tableMap.insert("TM-REPS-51",QString::number(i));i++;
    tableMap.insert("TM-REPS-52",QString::number(i));i++;
    tableMap.insert("TM-REPS-53",QString::number(i));i++;
    tableMap.insert("TM-REPS-54",QString::number(i));i++;
    tableMap.insert("TM-REPS-55",QString::number(i));i++;
    tableMap.insert("TM-REPS-56",QString::number(i));i++;
    tableMap.insert("TM-REPS-57",QString::number(i));i++;
    tableMap.insert("TM-REPS-58",QString::number(i));i++;
    tableMap.insert("TM-REPS-59",QString::number(i));i++;
    tableMap.insert("TM-REPS-60",QString::number(i));i++;
    tableMap.insert("TM-REPS-61",QString::number(i));i++;
    tableMap.insert("TM-REPS-62",QString::number(i));i++;
    tableMap.insert("TM-REPS-63",QString::number(i));i++;
    tableMap.insert("TM-REPS-64",QString::number(i));i++;
    tableMap.insert("TM-REPS-65",QString::number(i));i++;
    tableMap.insert("TM-REPS-66",QString::number(i));i++;
    tableMap.insert("TM-REPS-67",QString::number(i));i++;
    tableMap.insert("TM-REPS-68",QString::number(i));i++;
    tableMap.insert("TM-REPS-69",QString::number(i));i++;
    tableMap.insert("TM-REPS-70",QString::number(i));i++;
    tableMap.insert("TM-REPS-71",QString::number(i));i++;
    tableMap.insert("TM-REPS-72",QString::number(i));i++;
    tableMap.insert("TM-REPS-73",QString::number(i));i++;
    tableMap.insert("TM-REPS-74",QString::number(i));i++;
    tableMap.insert("TM-REPS-75",QString::number(i));i++;
    tableMap.insert("TM-REPS-76",QString::number(i));i++;
    tableMap.insert("TM-REPS-77",QString::number(i));i++;
    tableMap.insert("TM-REPS-78",QString::number(i));i++;
    tableMap.insert("TM-REPS-79",QString::number(i));i++;
    tableMap.insert("TM-REPS-80",QString::number(i));i++;
    tableMap.insert("TM-REPS-81",QString::number(i));i++;
    tableMap.insert("TM-REPS-82",QString::number(i));i++;
    tableMap.insert("TM-REPS-83",QString::number(i));i++;
    tableMap.insert("TM-REPS-84",QString::number(i));i++;
    tableMap.insert("TM-REPS-85",QString::number(i));i++;
    tableMap.insert("TM-REPS-86",QString::number(i));i++;
    tableMap.insert("TM-REPS-87",QString::number(i));i++;
    tableMap.insert("TM-REPS-88",QString::number(i));i++;
    tableMap.insert("TM-REPS-89",QString::number(i));i++;
    tableMap.insert("TM-REPS-90",QString::number(i));i++;
    tableMap.insert("TM-REPS-91",QString::number(i));i++;
    tableMap.insert("TM-REPS-92",QString::number(i));i++;
    tableMap.insert("TM-REPS-93",QString::number(i));i++;
    tableMap.insert("TM-REPS-94",QString::number(i));i++;
    tableMap.insert("TM-REPS-95",QString::number(i));i++;
    tableMap.insert("TM-REPS-96",QString::number(i));i++;
    tableMap.insert("TM-REPS-97",QString::number(i));i++;
    tableMap.insert("TM-REPS-98",QString::number(i));i++;
    tableMap.insert("TM-REPS-99",QString::number(i));i++;
    tableMap.insert("TM-REPS-100",QString::number(i));i++;
    tableMap.insert("TM-REPS-101",QString::number(i));i++;
    tableMap.insert("TM-REPS-102",QString::number(i));i++;
    tableMap.insert("TM-REPS-103",QString::number(i));i++;
    tableMap.insert("TM-REPS-104",QString::number(i));i++;
    tableMap.insert("TM-REPS-105",QString::number(i));i++;
    tableMap.insert("TM-REPS-106",QString::number(i));i++;
    tableMap.insert("TM-REPS-107",QString::number(i));i++;
    tableMap.insert("TM-REPS-108",QString::number(i));i++;
    tableMap.insert("TM-REPS-109",QString::number(i));i++;
    tableMap.insert("TM-REPS-110",QString::number(i));i++;
    tableMap.insert("TM-REPS-111",QString::number(i));i++;
    tableMap.insert("TM-REPS-112",QString::number(i));i++;
    tableMap.insert("TM-REPS-113",QString::number(i));i++;
    tableMap.insert("TM-REPS-114",QString::number(i));i++;
    tableMap.insert("TM-REPS-115",QString::number(i));i++;
    tableMap.insert("TM-REPS-116",QString::number(i));i++;
    tableMap.insert("TM-REPS-117",QString::number(i));i++;
    tableMap.insert("TM-REPS-118",QString::number(i));i++;
    tableMap.insert("TM-REPS-119",QString::number(i));i++;
    tableMap.insert("TM-REPS-120",QString::number(i));i++;
    tableMap.insert("TM-REPS-121",QString::number(i));i++;
    tableMap.insert("TM-REPS-122",QString::number(i));i++;
    tableMap.insert("TM-REPS-123",QString::number(i));i++;
    tableMap.insert("TM-REPS-124",QString::number(i));i++;
    tableMap.insert("TM-REPS-125",QString::number(i));i++;
    tableMap.insert("TM-REPS-126",QString::number(i));i++;
    tableMap.insert("TM-REPS-127",QString::number(i));i++;
    tableMap.insert("TM-REPS-128",QString::number(i));i++;
    tableMap.insert("TM-REPS-129",QString::number(i));i++;
    tableMap.insert("TM-REPS-130",QString::number(i));i++;
    tableMap.insert("TM-REPS-131",QString::number(i));i++;
    tableMap.insert("TM-REPS-132",QString::number(i));i++;
    tableMap.insert("TM-REPS-133",QString::number(i));i++;
    tableMap.insert("TM-REPS-134",QString::number(i));i++;
    tableMap.insert("TM-REPS-135",QString::number(i));i++;
    tableMap.insert("TM-REPS-136",QString::number(i));i++;
    tableMap.insert("TM-REPS-137",QString::number(i));i++;
    tableMap.insert("TM-REPS-138",QString::number(i));i++;
    tableMap.insert("TM-REPS-139",QString::number(i));i++;
    tableMap.insert("TM-REPS-140",QString::number(i));i++;
    tableMap.insert("TM-REPS-141",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-01",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-02",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-03",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-04",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-05",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-06",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-07",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-08",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-09",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-10",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-11",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-12",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-13",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-14",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-15",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-16",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-17",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-18",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-19",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-20",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-21",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-22",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-23",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-24",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-25",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-26",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-27",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-28",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-29",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-30",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-31",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-32",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-33",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-34",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-35",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-36",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-37",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-38",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-39",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-40",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-41",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-42",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-43",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-44",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-45",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-46",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-47",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-48",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-49",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-50",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-51",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-52",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-53",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-54",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-55",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-56",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-57",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-58",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-59",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-60",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-61",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-62",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-63",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-64",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-65",QString::number(i));i++;
    tableMap.insert("TM-RGNSS-66",QString::number(i));i++;
    tableMap.insert("TM-RZH-01",QString::number(i));i++;
    tableMap.insert("TM-RZH-02",QString::number(i));i++;
    tableMap.insert("TM-RZH-03",QString::number(i));i++;
    tableMap.insert("TM-RZH-04",QString::number(i));i++;
    tableMap.insert("TM-RZH-05",QString::number(i));i++;
    tableMap.insert("TM-RZH-06",QString::number(i));i++;
    tableMap.insert("TM-RZH-07",QString::number(i));i++;
    tableMap.insert("TM-RZH-08",QString::number(i));i++;
    tableMap.insert("TM-RZH-09",QString::number(i));i++;
    tableMap.insert("TM-RZH-10",QString::number(i));i++;
    tableMap.insert("TM-RZH-11",QString::number(i));i++;
    tableMap.insert("TM-RZH-12",QString::number(i));i++;
    tableMap.insert("TM-RZH-13",QString::number(i));i++;
    tableMap.insert("TM-RZH-14",QString::number(i));i++;
    tableMap.insert("TM-RZH-15",QString::number(i));i++;
    tableMap.insert("TM-RZH-16",QString::number(i));i++;
    tableMap.insert("TM-RZH-17",QString::number(i));i++;
    tableMap.insert("TM-RZH-18",QString::number(i));i++;
    tableMap.insert("TM-RZH-19",QString::number(i));i++;
    tableMap.insert("TM-RZH-20",QString::number(i));i++;
    tableMap.insert("TM-RZH-21",QString::number(i));i++;
    tableMap.insert("TM-RZH-22",QString::number(i));i++;
    tableMap.insert("TM-RZH-23",QString::number(i));i++;
    tableMap.insert("TM-RZH-24",QString::number(i));i++;
    tableMap.insert("TM-RZH-25",QString::number(i));i++;
    tableMap.insert("TM-RZH-26",QString::number(i));i++;
    tableMap.insert("TM-RZH-27",QString::number(i));i++;
    tableMap.insert("TM-RZH-28",QString::number(i));i++;
    tableMap.insert("TM-RZH-29",QString::number(i));i++;
    tableMap.insert("TM-RZH-30",QString::number(i));i++;
    tableMap.insert("TM-RZH-31",QString::number(i));i++;
    tableMap.insert("TM-RZH-32",QString::number(i));i++;
    tableMap.insert("TM-RZH-33",QString::number(i));i++;
    tableMap.insert("TM-RZH-34",QString::number(i));i++;
    tableMap.insert("TM-RZH-35",QString::number(i));i++;
    tableMap.insert("TM-RZH-36",QString::number(i));i++;
    tableMap.insert("TM-RZH-37",QString::number(i));i++;
    tableMap.insert("TM-RZH-38",QString::number(i));i++;
    tableMap.insert("TM-RZH-39",QString::number(i));i++;
    tableMap.insert("TM-RZH-40",QString::number(i));i++;
    tableMap.insert("TM-RZH-41",QString::number(i));i++;
    tableMap.insert("TM-RZH-42",QString::number(i));i++;
    tableMap.insert("TM-RZH-43",QString::number(i));i++;
    tableMap.insert("TM-RZH-44",QString::number(i));i++;
    tableMap.insert("TM-RZH-45",QString::number(i));i++;
    tableMap.insert("TM-RZH-46",QString::number(i));i++;
    tableMap.insert("TM-RZH-47",QString::number(i));i++;
    tableMap.insert("TM-RZH-48",QString::number(i));i++;
    tableMap.insert("TM-RZH-49",QString::number(i));i++;
    tableMap.insert("TM-RZH-50",QString::number(i));i++;
    tableMap.insert("TM-RZH-51",QString::number(i));i++;
    tableMap.insert("TM-RZH-52",QString::number(i));i++;
    tableMap.insert("TM-RZH-53",QString::number(i));i++;
    tableMap.insert("TM-RZH-54",QString::number(i));i++;
    tableMap.insert("TM-RZH-55",QString::number(i));i++;
    tableMap.insert("TM-RZH-56",QString::number(i));i++;
    tableMap.insert("TM-RZH-57",QString::number(i));i++;
    tableMap.insert("TM-RZH-58",QString::number(i));i++;
    tableMap.insert("TM-RZH-59",QString::number(i));i++;
    tableMap.insert("TM-RZH-60",QString::number(i));i++;
    tableMap.insert("TM-RZH-61",QString::number(i));i++;
    tableMap.insert("TM-RZH-62",QString::number(i));i++;
    tableMap.insert("TM-RZH-63",QString::number(i));i++;
    tableMap.insert("TM-RZH-64",QString::number(i));i++;
    tableMap.insert("TM-RZH-65",QString::number(i));i++;
    tableMap.insert("TM-RZH-66",QString::number(i));i++;
    tableMap.insert("TM-RZH-67",QString::number(i));i++;
    tableMap.insert("TM-RZH-68",QString::number(i));i++;
    tableMap.insert("TM-RZH-69",QString::number(i));i++;
    tableMap.insert("TM-RZH-70",QString::number(i));i++;
    tableMap.insert("TM-RZH-71",QString::number(i));i++;
    tableMap.insert("TM-RZH-72",QString::number(i));i++;
    tableMap.insert("TM-RZH-73",QString::number(i));i++;
    tableMap.insert("TM-RZH-74",QString::number(i));i++;
    tableMap.insert("TM-RZH-75",QString::number(i));i++;
    tableMap.insert("TM-RZH-76",QString::number(i));i++;
    tableMap.insert("TM-RZH-77",QString::number(i));i++;
    tableMap.insert("TM-RZH-78",QString::number(i));i++;
    tableMap.insert("TM-RZH-79",QString::number(i));i++;
    tableMap.insert("TM-RZH-80",QString::number(i));i++;
    tableMap.insert("TM-RZH-81",QString::number(i));i++;
    tableMap.insert("TM-RZH-82",QString::number(i));i++;
    tableMap.insert("TM-RZH-83",QString::number(i));i++;
    tableMap.insert("TM-RZH-84",QString::number(i));i++;
    tableMap.insert("TM-RZH-85",QString::number(i));i++;
    tableMap.insert("TM-RZH-86",QString::number(i));i++;
    tableMap.insert("TM-RZH-87",QString::number(i));i++;
    tableMap.insert("TM-RZH-88",QString::number(i));i++;
    tableMap.insert("TM-RZH-89",QString::number(i));i++;
    tableMap.insert("TM-RZH-90",QString::number(i));i++;
    tableMap.insert("TM-RZH-91",QString::number(i));i++;
    tableMap.insert("TM-RZH-92",QString::number(i));i++;
    tableMap.insert("TM-RZH-93",QString::number(i));i++;
    tableMap.insert("TM-RZH-94",QString::number(i));i++;
    tableMap.insert("TM-RZH-95",QString::number(i));i++;
    tableMap.insert("TM-RZH-96",QString::number(i));i++;
    tableMap.insert("TM-RZH-97",QString::number(i));i++;
    tableMap.insert("TM-RZH-98",QString::number(i));i++;
    tableMap.insert("TM-RZH-99",QString::number(i));i++;
    tableMap.insert("TM-RZH-100",QString::number(i));i++;
    tableMap.insert("TM-RZH-101",QString::number(i));i++;
    tableMap.insert("TM-RCES-01",QString::number(i));i++;
    tableMap.insert("TM-RCES-02",QString::number(i));i++;
    tableMap.insert("TM-RCES-03",QString::number(i));i++;
    tableMap.insert("TM-RCES-04",QString::number(i));i++;
    tableMap.insert("TM-RCES-05",QString::number(i));i++;
    tableMap.insert("TM-RCES-06",QString::number(i));i++;
    tableMap.insert("TM-RCES-07",QString::number(i));i++;
    tableMap.insert("TM-RCES-08",QString::number(i));i++;
    tableMap.insert("TM-RCES-09",QString::number(i));i++;
    tableMap.insert("TM-RCES-10",QString::number(i));i++;
    tableMap.insert("TM-RCES-11",QString::number(i));i++;
    tableMap.insert("TM-RCES-12",QString::number(i));i++;
    tableMap.insert("TM-RCES-13",QString::number(i));i++;
    tableMap.insert("TM-RCES-14",QString::number(i));i++;
    tableMap.insert("TM-RCES-15",QString::number(i));i++;
    tableMap.insert("TM-RCES-16",QString::number(i));i++;
    tableMap.insert("TM-RCES-17",QString::number(i));i++;
    tableMap.insert("TM-RCES-18",QString::number(i));i++;
    tableMap.insert("TM-RCES-19",QString::number(i));i++;
    tableMap.insert("TM-RCES-20",QString::number(i));i++;
    tableMap.insert("TM-RCES-21",QString::number(i));i++;
    tableMap.insert("TM-RCES-22",QString::number(i));i++;
    tableMap.insert("TM-RCES-23",QString::number(i));i++;
    tableMap.insert("TM-RCES-24",QString::number(i));i++;
    tableMap.insert("TM-RCES-25",QString::number(i));i++;
    tableMap.insert("TM-RCES-26",QString::number(i));i++;
    tableMap.insert("TM-RCES-27",QString::number(i));i++;
    tableMap.insert("TM-RCES-28",QString::number(i));i++;
    tableMap.insert("TM-RCES-29",QString::number(i));i++;
    tableMap.insert("TM-RCES-30",QString::number(i));i++;
    tableMap.insert("TM-RCES-31",QString::number(i));i++;
    tableMap.insert("TM-RCES-32",QString::number(i));i++;
    tableMap.insert("TM-RCES-33",QString::number(i));i++;
    tableMap.insert("TM-RCES-34",QString::number(i));i++;
    tableMap.insert("TM-RCES-35",QString::number(i));i++;
    tableMap.insert("TM-RCES-36",QString::number(i));i++;
    tableMap.insert("TM-RCES-37",QString::number(i));i++;
    tableMap.insert("TM-RCES-38",QString::number(i));i++;
    tableMap.insert("TM-RCES-39",QString::number(i));i++;
    tableMap.insert("TM-RCES-40",QString::number(i));i++;
    tableMap.insert("TM-RCES-41",QString::number(i));i++;
    tableMap.insert("TM-RCES-42",QString::number(i));i++;
    tableMap.insert("TM-RCES-43",QString::number(i));i++;
    tableMap.insert("TM-RCES-44",QString::number(i));i++;
    tableMap.insert("TM-RCES-45",QString::number(i));i++;
    tableMap.insert("TM-RCES-46",QString::number(i));i++;
    tableMap.insert("TM-RCES-47",QString::number(i));i++;
    tableMap.insert("TM-RCES-48",QString::number(i));i++;
    tableMap.insert("TM-RCES-49",QString::number(i));i++;
    tableMap.insert("TM-RCES-50",QString::number(i));i++;
    tableMap.insert("TM-RCES-51",QString::number(i));i++;
    tableMap.insert("TM-RCES-52",QString::number(i));i++;
    tableMap.insert("TM-RCES-53",QString::number(i));i++;
    tableMap.insert("TM-RCES-54",QString::number(i));i++;
    tableMap.insert("TM-RCES-55",QString::number(i));i++;
    tableMap.insert("TM-RCES-56",QString::number(i));i++;
    tableMap.insert("TM-RCES-57",QString::number(i));i++;
    tableMap.insert("TM-RCES-58",QString::number(i));i++;
    tableMap.insert("TM-RCES-59",QString::number(i));i++;
    tableMap.insert("TM-RCES-60",QString::number(i));i++;
    tableMap.insert("TM-RCES-61",QString::number(i));i++;
    tableMap.insert("TM-RCES-62",QString::number(i));i++;
    tableMap.insert("TM-RCES-63",QString::number(i));i++;
    tableMap.insert("TM-RCES-64",QString::number(i));i++;
    tableMap.insert("TM-RCES-65",QString::number(i));i++;
    tableMap.insert("TM-RCES-66",QString::number(i));i++;
    tableMap.insert("TM-RCES-67",QString::number(i));i++;
    tableMap.insert("TM-RCES-68",QString::number(i));i++;
    tableMap.insert("TM-RCES-69",QString::number(i));i++;
    tableMap.insert("TM-RCES-70",QString::number(i));i++;
    tableMap.insert("TM-RCES-71",QString::number(i));i++;
    tableMap.insert("TM-RCES-72",QString::number(i));i++;
    tableMap.insert("TM-RCES-73",QString::number(i));i++;
    tableMap.insert("TM-RCES-74",QString::number(i));i++;
    tableMap.insert("TM-RCES-75",QString::number(i));i++;
    tableMap.insert("TM-RCES-76",QString::number(i));i++;
    tableMap.insert("TM-RCES-77",QString::number(i));i++;
    tableMap.insert("TM-RCES-78",QString::number(i));i++;
    tableMap.insert("TM-RCES-79",QString::number(i));i++;
    tableMap.insert("TM-RCES-80",QString::number(i));i++;
    tableMap.insert("TM-RCES-81",QString::number(i));i++;
    tableMap.insert("TM-RCES-82",QString::number(i));i++;
    tableMap.insert("TM-RCES-83",QString::number(i));i++;
    tableMap.insert("TM-RCES-84",QString::number(i));i++;
    tableMap.insert("TM-RCES-85",QString::number(i));i++;
    tableMap.insert("TM-RCES-86",QString::number(i));i++;
    tableMap.insert("TM-RCES-87",QString::number(i));i++;
    tableMap.insert("TM-RCES-88",QString::number(i));i++;
    tableMap.insert("TM-RCES-89",QString::number(i));i++;
    tableMap.insert("TM-RCES-90",QString::number(i));i++;
    tableMap.insert("TM-RCES-93",QString::number(i));i++;
    tableMap.insert("TM-RCES-94",QString::number(i));i++;
    tableMap.insert("TM-RCES-95",QString::number(i));i++;
    tableMap.insert("TM-RCES-96",QString::number(i));i++;
    tableMap.insert("TM-RCES-97",QString::number(i));i++;
    tableMap.insert("TM-RCES-98",QString::number(i));i++;
    tableMap.insert("TM-RCES-99",QString::number(i));i++;
    tableMap.insert("TM-RCES-100",QString::number(i));i++;
    tableMap.insert("TM-RCES-101",QString::number(i));i++;
    tableMap.insert("TM-RCES-102",QString::number(i));i++;
    tableMap.insert("TM-RCES-103",QString::number(i));i++;
    tableMap.insert("TM-RCES-104",QString::number(i));i++;
    tableMap.insert("TM-RCES-105",QString::number(i));i++;
    tableMap.insert("TM-RCES-106",QString::number(i));i++;
    tableMap.insert("TM-RCES-107",QString::number(i));i++;
    tableMap.insert("TM-RCES-108",QString::number(i));i++;
    tableMap.insert("TM-RCES-109",QString::number(i));i++;
    tableMap.insert("TM-RCES-110",QString::number(i));i++;
    tableMap.insert("TM-RCES-111",QString::number(i));i++;
    tableMap.insert("TM-RCES-112",QString::number(i));i++;
    tableMap.insert("TM-RCES-113",QString::number(i));i++;
    tableMap.insert("TM-RCES-114",QString::number(i));i++;
    tableMap.insert("TM-RCES-115",QString::number(i));i++;
    tableMap.insert("TM-RCES-116",QString::number(i));i++;
    tableMap.insert("TM-RCES-117",QString::number(i));i++;
    tableMap.insert("TM-RCES-118",QString::number(i));i++;
    tableMap.insert("TM-RCES-119",QString::number(i));i++;
    tableMap.insert("TM-RCES-120",QString::number(i));i++;
    tableMap.insert("TM-RCES-121",QString::number(i));i++;
    tableMap.insert("TM-RCES-122",QString::number(i));i++;
    tableMap.insert("TM-RCES-123",QString::number(i));i++;
    tableMap.insert("TM-RCES-124",QString::number(i));i++;
    tableMap.insert("TM-RCES-125",QString::number(i));i++;
    tableMap.insert("TM-RCES-126",QString::number(i));i++;
    tableMap.insert("TM-RCES-127",QString::number(i));i++;
    tableMap.insert("TM-RCES-128",QString::number(i));i++;
    tableMap.insert("TM-RCES-129",QString::number(i));i++;
    tableMap.insert("TM-RCES-130",QString::number(i));i++;
    tableMap.insert("TM-RCES-131",QString::number(i));i++;
    tableMap.insert("TM-RCES-132",QString::number(i));i++;
    tableMap.insert("TM-RCES-133",QString::number(i));i++;
    tableMap.insert("TM-RCES-134",QString::number(i));i++;
    tableMap.insert("TM-RCES-135",QString::number(i));i++;
    tableMap.insert("TM-RCES-136",QString::number(i));i++;
    tableMap.insert("TM-RCES-137",QString::number(i));i++;
    tableMap.insert("TM-RCES-138",QString::number(i));i++;
    tableMap.insert("TM-RCES-139",QString::number(i));i++;
    tableMap.insert("TM-RCES-140",QString::number(i));i++;
    tableMap.insert("TM-RCES-141",QString::number(i));i++;
    tableMap.insert("TM-RCES-142",QString::number(i));i++;
    tableMap.insert("TM-RCES-143",QString::number(i));i++;
    tableMap.insert("TM-RCES-144",QString::number(i));i++;
    tableMap.insert("TM-RCES-145",QString::number(i));i++;
    tableMap.insert("TM-RCES-146",QString::number(i));i++;
    tableMap.insert("TM-RCES-147",QString::number(i));i++;
    tableMap.insert("TM-RCES-148",QString::number(i));i++;
    tableMap.insert("TM-RCES-149",QString::number(i));i++;
    tableMap.insert("TM-RCES-150",QString::number(i));i++;
    tableMap.insert("TM-RCES-151",QString::number(i));i++;
    tableMap.insert("TM-RCES-152",QString::number(i));i++;
    tableMap.insert("TM-RCES-153",QString::number(i));i++;
    tableMap.insert("TM-RCES-154",QString::number(i));i++;
    tableMap.insert("TM-RCES-155",QString::number(i));i++;
    tableMap.insert("TM-RCES-156",QString::number(i));i++;
    tableMap.insert("TM-RCES-157",QString::number(i));i++;
    tableMap.insert("TM-RCES-158",QString::number(i));i++;
    tableMap.insert("TM-RCES-159",QString::number(i));i++;
    tableMap.insert("TM-RCES-160",QString::number(i));i++;
    tableMap.insert("TM-RCES-161",QString::number(i));i++;
    tableMap.insert("TM-RCES-162",QString::number(i));i++;
    tableMap.insert("TM-RCES-163",QString::number(i));i++;
    tableMap.insert("TM-RCES-164",QString::number(i));i++;
    tableMap.insert("TM-RCES-165",QString::number(i));i++;
    tableMap.insert("TM-RCES-166",QString::number(i));i++;
    tableMap.insert("TM-RCES-167",QString::number(i));i++;
    tableMap.insert("TM-RCES-168",QString::number(i));i++;
    tableMap.insert("TM-RCES-169",QString::number(i));i++;
    tableMap.insert("TM-RCES-170",QString::number(i));i++;
    tableMap.insert("TM-RCES-171",QString::number(i));i++;
    tableMap.insert("TM-RCES-172",QString::number(i));i++;
    tableMap.insert("TM-RCES-173",QString::number(i));i++;
    tableMap.insert("TM-RCES-174",QString::number(i));i++;
    tableMap.insert("TM-RCES-175",QString::number(i));i++;
    tableMap.insert("TM-RCES-176",QString::number(i));i++;
    tableMap.insert("TM-RCES-177",QString::number(i));i++;
    tableMap.insert("TM-RCES-178",QString::number(i));i++;
    tableMap.insert("TM-RCES-179",QString::number(i));i++;
    tableMap.insert("TM-RCES-180",QString::number(i));i++;
    tableMap.insert("TM-RCES-181",QString::number(i));i++;
    tableMap.insert("TM-RCES-182",QString::number(i));i++;
    tableMap.insert("TM-RCES-183",QString::number(i));i++;
    tableMap.insert("TM-RCES-184",QString::number(i));i++;
    tableMap.insert("TM-RCES-185",QString::number(i));i++;
    tableMap.insert("TM-RCES-186",QString::number(i));i++;
    tableMap.insert("TM-RCES-187",QString::number(i));i++;
    tableMap.insert("TM-RCES-188",QString::number(i));i++;
    tableMap.insert("TM-RCES-189",QString::number(i));i++;
    tableMap.insert("TM-RCES-190",QString::number(i));i++;
    tableMap.insert("TM-RCES-191",QString::number(i));i++;
    tableMap.insert("TM-RCES-192",QString::number(i));i++;
    tableMap.insert("TM-RCES-193",QString::number(i));i++;
    tableMap.insert("TM-RCES-194",QString::number(i));i++;
    tableMap.insert("TM-RCES-195",QString::number(i));i++;
    tableMap.insert("TM-RCES-196",QString::number(i));i++;
    tableMap.insert("TM-RCES-197",QString::number(i));i++;
    tableMap.insert("TM-RCES-198",QString::number(i));i++;
    tableMap.insert("TM-RCES-199",QString::number(i));i++;
    tableMap.insert("TM-RCES-200",QString::number(i));i++;
    tableMap.insert("TM-RCES-201",QString::number(i));i++;
    tableMap.insert("TM-RCES-202",QString::number(i));i++;
    tableMap.insert("TM-RCES-203",QString::number(i));i++;
    tableMap.insert("TM-RCES-204",QString::number(i));i++;
    tableMap.insert("TM-RCES-205",QString::number(i));i++;
    tableMap.insert("TM-RCES-206",QString::number(i));i++;
    tableMap.insert("TM-RCES-207",QString::number(i));i++;
    tableMap.insert("TM-RCES-208",QString::number(i));i++;
    tableMap.insert("TM-RCES-209",QString::number(i));i++;
    tableMap.insert("TM-RCES-210",QString::number(i));i++;
    tableMap.insert("TM-RCES-211",QString::number(i));i++;
    tableMap.insert("TM-RCES-212",QString::number(i));i++;
    tableMap.insert("TM-RCES-213",QString::number(i));i++;
    tableMap.insert("TM-RCES-214",QString::number(i));i++;
    tableMap.insert("TM-RCES-215",QString::number(i));i++;
    tableMap.insert("TM-RCES-216",QString::number(i));i++;
    tableMap.insert("TM-RCES-217",QString::number(i));i++;
    tableMap.insert("TM-RCES-218",QString::number(i));i++;
    tableMap.insert("TM-RCES-219",QString::number(i));i++;
    tableMap.insert("TM-RCES-220",QString::number(i));i++;
    tableMap.insert("TM-RCES-221",QString::number(i));i++;
    tableMap.insert("TM-RCES-222",QString::number(i));i++;
    tableMap.insert("TM-RCES-223",QString::number(i));i++;
    tableMap.insert("TM-RCES-224",QString::number(i));i++;
    tableMap.insert("TM-RCES-225",QString::number(i));i++;
    tableMap.insert("TM-RCES-226",QString::number(i));i++;
    tableMap.insert("TM-RCES-227",QString::number(i));i++;
    tableMap.insert("TM-RCES-228",QString::number(i));i++;
    tableMap.insert("TM-RCES-229",QString::number(i));i++;
    tableMap.insert("TM-RCES-230",QString::number(i));i++;
    tableMap.insert("TM-RCES-231",QString::number(i));i++;
    tableMap.insert("TM-RCES-232",QString::number(i));i++;
    tableMap.insert("TM-RCES-233",QString::number(i));i++;
    tableMap.insert("TM-RCES-234",QString::number(i));i++;
    tableMap.insert("TM-RCES-235",QString::number(i));i++;
    tableMap.insert("TM-RCES-236",QString::number(i));i++;
    tableMap.insert("TM-RCES-237",QString::number(i));i++;
    tableMap.insert("TM-RCES-238",QString::number(i));i++;
    tableMap.insert("TM-ROS-01",QString::number(i));i++;
    tableMap.insert("TM-ROS-02",QString::number(i));i++;
    tableMap.insert("TM-ROS-03",QString::number(i));i++;
    tableMap.insert("TM-ROS-04",QString::number(i));i++;
    tableMap.insert("TM-ROS-05",QString::number(i));i++;
    tableMap.insert("TM-ROS-06",QString::number(i));i++;
}


